---
title: "0420corpus"
author: "Brick"
date: "2024-04-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


本 R markdown 筆記本用於處理corpus數據集。
首先，對此數據做一簡單介紹：
Brown Corpus是著名的英文語料庫，內含若干篇文字材料。建立數據集的步驟如下：
1. 統計出語料庫中出現頻率最高的300個單詞（排除出現次數最多的若干詞），記為T300
2. 對T300中每一個詞，找到其在語料庫中出現的位置（可能出現成百上千次）
3. 從此位置出發，向左和向右各檢查兩個單詞，查看是否有T300中的單詞。
4. 對A,B,C都是T300中的詞，每次在A詞左邊1格或2格的位置見到B詞，就在數據集的第A行，第B列加1；每次在A詞右邊1格或2格的位置見到C詞，就在數據集的第A行，第300+C列的位置加1。


# 引入必要的庫

```{r message=FALSE, warning=FALSE}
# install.packages("Rdimtools")
library(Rdimtools) # 用於實施拉普拉斯特征映射
library(plotly) # 用於交互式繪圖
```


# 檢查數據

```{r}
setwd("D:/Study/Courses/2024Spring/multivariate/Project/code/0511seg")
rawdf <- read.csv("pineapple.csv")
# 表格的第一列是單詞名，故排掉
df <- rawdf[sample(1:90000,2000),]
```

```{r}
head(df)
```


## 找拉普拉斯特征映射

```{r}
# 準備
tt <- 1e4
method <- "knn" # 選KNN還是ENN?
k <- 3 # 找幾個鄰居？
epsilon <- 0.5 # 相鄰的閾值？（初得到數據集不了解其距離尺度，需要多探索）

# 將數據框轉換成矩陣，便於調用函數
# scale 意味著行和列的分離：你把列當做屬性，而不是什麼可以和行任意調換的東西
# 但 scale意味著你認為兩列之間沒有可比性。
df_mat <- as.matrix(df, nrows=nrow(df))

```





```{r}
# Generating 3d scatter plot
library(plotly)
fig <- plot_ly(df, x=~x,y=~y,z=~255-gray_value,color=~gray_value,size = c(0.8))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = 'x'),
                     yaxis = list(title = 'y'),
                     zaxis = list(title = 'intensity')))

fig
```

